/**
 * error-reporter.ts
 *
 * Calls the satellite's `report_error` update function directly via the Juno
 * actor pattern — bypassing satellite.api.ts which is regenerated by
 * `juno functions build` and may not retain the `functions` export.
 *
 * Returns the `error_id` (format: "err_{nanoseconds}", e.g. "err_1772598984825320076")
 * which is ALSO the Juno document key. Show it to the user so they can give it
 * to support; devs filter by it in the admin key-matcher.
 * Never throws — error reporting must never disrupt the caller.
 */
import type {
  _SERVICE as SatelliteActor,
  ErrorPayload,
} from "@/declarations/satellite/satellite.did";
import {idlFactory} from "@/declarations/satellite/satellite.factory.did.js";
import {getSatelliteExtendedActor} from "@junobuild/core";

const satelliteReportError = async (payload: ErrorPayload) => {
  const {report_error} = await getSatelliteExtendedActor<SatelliteActor>({
    idlFactory,
  });
  return await report_error(payload);
};

/**
 * Reports an error to the satellite and returns the error_id (= doc key) or null.
 * Fire-and-forget friendly — catches any failure internally.
 */
export async function reportError(
  component: string,
  message: string,
  rawError: string
): Promise<string | null> {
  try {
    const result = await satelliteReportError({
      component: component.slice(0, 100),
      message: message.slice(0, 500),
      raw_error: rawError.slice(0, 2000),
    });

    if ("Ok" in result) {
      return result.Ok;
    }
    return null;
  } catch {
    // Best-effort: error reporting must never disrupt the caller.
    return null;
  }
}
