[project]

name = "tresr-game"
revision = "1.0"

[default]

# No provider defined here.
# Will refer to  ~/.config/secretspec/config.toml

[profiles]

[profiles.default]

#########################
# DaisyUI
#########################

DAISYUI_LICENSE = { description = "DaisyUI license", required = false }
DAISYUI_EMAIL = { description = "DaisyUI email", required = false }

#########################
# Avalanche (Foundry)
#########################

DEPLOYER_PRIVATE_KEY = { description = "Deployer wallet private key", required = false }
SNOWTRACE_API_KEY = { description = "Snowtrace API key for contract verification (for Fuji and Mainnet)", required = false }

#########################
# Wallet Connect Cloud
#########################

PUBLIC_WALLETCONNECT_PROJECT_ID = { description = "Wallet Connect Cloud project ID (PUBLIC_ prefix for Astro client exposure)", required = false }
