name: Test Skip
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job 1"
  job2:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "Job 2"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: always()
    steps:
      - run: echo "Job 3"
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - run: echo "Job 4"
  job5:
    runs-on: ubuntu-latest
    needs: job3
    if: success()
    steps:
      - run: echo "Job 5"
