---
name: Cache Bun
description: Cache Bun's global package install cache.

runs:
  using: composite
  steps:
    - id: cache_bun
      name: Cache Bun
      uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: bun-${{ runner.os }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          bun-${{ runner.os }}-
