#![allow(dead_code)]

use crate::evm_rpc_types::{
    BlockTag, CallArgs, CallResult as EvmCallResult, EvmRpcCanister, GetTransactionCountArgs,
    GetTransactionCountResult, GetTransactionReceiptResult, MultiCallResult,
    MultiGetTransactionCountResult, MultiGetTransactionReceiptResult, RequestResult, RpcApi,
    RpcConfig, RpcService, RpcServices, TransactionRequest,
};
use candid::Principal;
use ic_cdk::management_canister::{
    EcdsaCurve, EcdsaKeyId, EcdsaPublicKeyArgs, SignWithEcdsaArgs, ecdsa_public_key,
    sign_with_ecdsa as mgmt_sign_with_ecdsa,
};
use libsecp256k1::{Message, RecoveryId, Signature, recover};
use num_bigint::BigUint;
use num_traits::ToPrimitive;
use rlp::RlpStream;
use tiny_keccak::{Hasher, Keccak};

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/// ECDSA key ID for signing transactions (generated by build.rs from SATELLITE_NETWORK)
const ECDSA_KEY_NAME: &str = crate::config::ECDSA_KEY_NAME;

/// Default gas parameters (fallback when dynamic estimation fails)
const DEFAULT_GAS_LIMIT: u64 = 21000;
const DEFAULT_GAS_PRICE: u64 = 25_000_000_000; // 25 Gwei

/// Base cycles for an EVM RPC call. The IC charges per byte of HTTP response,
/// so larger responses (like getTransactionReceipt) need more budget.
const BASE_CYCLES: u128 = 1_000_000_000; // 1B base

/// Calculate cycle budget for an EVM RPC call.
/// `max_response_bytes`: expected max response size.
fn cycles_for_call(max_response_bytes: u64) -> u128 {
    // IC charges ~400K cycles per KB of response on a 13-node subnet
    let response_cycles = (max_response_bytes as u128) * 400_000;
    let subtotal = BASE_CYCLES + response_cycles;

    // Network multiplier: local/testnet subnets are smaller (cheaper)
    if crate::config::NETWORK_NAME == "anvil" {
        subtotal // Local: use as-is
    } else {
        // 50% safety margin for production / testnet
        subtotal * 3 / 2
    }
}

/// Vault.payFee(uint256,bytes32) function selector
const PAY_FEE_SELECTOR: &str = "c6bbdafb";
/// Vault.claim(bytes32,uint256,uint256,bytes) function selector
const CLAIM_SELECTOR: &str = "95ace4b3";
/// ERC-20 transfer(address,uint256) function selector
const TRANSFER_SELECTOR: [u8; 4] = [0xa9, 0x05, 0x9c, 0xbb];

// ---------------------------------------------------------------------------
// Helpers: EvmRpcCanister construction & RPC service configuration
// ---------------------------------------------------------------------------

/// Build the `EvmRpcCanister` handle from the EVM RPC canister principal.
fn evm_rpc_canister() -> Result<EvmRpcCanister, String> {
    let principal = Principal::from_text(crate::config::EVM_RPC_CANISTER_ID)
        .map_err(|e| format!("Invalid EVM RPC canister ID: {:?}", e))?;
    Ok(EvmRpcCanister(principal))
}

/// Build `RpcServices::Custom` with the Avalanche RPC URLs from config.
/// Each URL becomes a separate `RpcService::Custom` provider so the canister
/// can achieve multi-provider consensus.
fn avalanche_rpc_services() -> RpcServices {
    let services: Vec<RpcApi> = crate::config::AVALANCHE_RPC_URLS
        .iter()
        .map(|url| RpcApi {
            url: url.to_string(),
            headers: None,
        })
        .collect();

    RpcServices::Custom {
        chainId: crate::config::AVALANCHE_CHAIN_ID,
        services,
    }
}

/// Default `RpcConfig` — use None (canister defaults) for most calls.
fn default_rpc_config() -> Option<RpcConfig> {
    None
}

// ---------------------------------------------------------------------------
// Helper: raw JSON-RPC via multi_request (for methods without typed bindings)
// ---------------------------------------------------------------------------

/// Send a raw JSON-RPC call through the EVM RPC canister's `request` method.
/// Used for methods that don't have typed bindings in evm-rpc-canister-types
/// (e.g. eth_getTransactionByHash, eth_gasPrice, eth_estimateGas).
async fn json_rpc_request(method: &str, params: &str) -> Result<String, String> {
    let canister = evm_rpc_canister()?;

    let json_body = format!(
        r#"{{"jsonrpc":"2.0","method":"{}","params":{},"id":1}}"#,
        method, params
    );

    let service = RpcService::Custom(RpcApi {
        url: crate::config::AVALANCHE_RPC_URLS[0].to_string(),
        headers: None,
    });

    let result = canister
        .request(service, json_body, 2048, cycles_for_call(2048))
        .await?;

    match result.0 {
        RequestResult::Ok(body) => Ok(body),
        RequestResult::Err(e) => Err(format!("RPC request error: {:?}", e)),
    }
}

/// Parse the JSON-RPC response body into the `result` field value.
fn parse_json_rpc_result(body: &str) -> Result<serde_json::Value, String> {
    let parsed: serde_json::Value = serde_json::from_str(body)
        .map_err(|e| format!("Failed to parse JSON-RPC response: {}", e))?;

    if let Some(error) = parsed.get("error") {
        let code = error.get("code").and_then(|c| c.as_i64()).unwrap_or(0);
        let message = error
            .get("message")
            .and_then(|m| m.as_str())
            .unwrap_or("unknown error");
        return Err(format!("RPC error {}: {}", code, message));
    }

    parsed
        .get("result")
        .cloned()
        .ok_or_else(|| "No 'result' field in JSON-RPC response".to_string())
}

// ---------------------------------------------------------------------------
// Public API: Fee verification
// ---------------------------------------------------------------------------

/// Verify a fee transaction on Avalanche.
/// Returns the parsed fee data including amount and sender address.
/// `caller_wallet` is used by the ANVIL mock to return the correct `from` address
/// so the wallet-match check in `on_fee_created` passes in local dev.
pub async fn verify_avalanche_fee(
    tx_hash: &str,
    caller_wallet: Option<&str>,
) -> Result<ParsedFee, String> {
    // Anvil mock: skip real RPC verification in local dev
    if crate::config::NETWORK_NAME == "anvil" {
        crate::logging::log_debug(
            "EvmRpc",
            &format!("ANVIL_MOCK: verify_avalanche_fee for {}", tx_hash),
        );
        // Echo back the caller's wallet so the from-address check passes.
        let from = caller_wallet
            .unwrap_or("0x0000000000000000000000000000000000000000")
            .to_string();
        return Ok(ParsedFee { amount: 10, from });
    }

    // eth_getTransactionByHash — no typed binding, use raw JSON-RPC
    let params = format!("[\"{}\"]", tx_hash);
    let body = json_rpc_request("eth_getTransactionByHash", &params).await?;
    let result_json = parse_json_rpc_result(&body)?;

    if result_json.is_null() {
        return Err("No transaction found".to_string());
    }

    let parsed = parse_fee_input(&result_json)?;

    // Verify the transaction actually succeeded on-chain
    verify_transaction_receipt(tx_hash).await?;

    Ok(parsed)
}

// ---------------------------------------------------------------------------
// Public API: Claim verification
// ---------------------------------------------------------------------------

/// Verify a claim transaction on Avalanche.
/// Parses the ABI calldata and verifies the selector, sessionId, amount, and keys
/// match the expected values from the claim record.
pub async fn verify_avalanche_claim_tx(
    tx_hash: &str,
    expected_session_id: &str,
    expected_amount: u64,
    expected_keys: u64,
) -> Result<(), String> {
    // Anvil mock: skip real RPC verification in local dev
    if crate::config::NETWORK_NAME == "anvil" {
        crate::logging::log_debug(
            "EvmRpc",
            &format!("ANVIL_MOCK: verify_avalanche_claim_tx for {}", tx_hash),
        );
        return Ok(());
    }

    // eth_getTransactionByHash — no typed binding, use raw JSON-RPC
    let params = format!("[\"{}\"]", tx_hash);
    let body = json_rpc_request("eth_getTransactionByHash", &params).await?;
    let result_json = parse_json_rpc_result(&body)?;

    if result_json.is_null() {
        return Err("Transaction not found".to_string());
    }

    verify_claim_transaction(
        &result_json,
        expected_session_id,
        expected_amount,
        expected_keys,
    )?;

    // Verify the transaction actually succeeded on-chain
    verify_transaction_receipt(tx_hash).await?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Internal: Claim & fee parsing (unchanged business logic)
// ---------------------------------------------------------------------------

/// Verify that the transaction is a valid claim to the vault contract.
/// Parses the ABI-encoded calldata and checks that the function selector is
/// `claim(bytes32,uint256,uint256,bytes)`, and that the sessionId, amount, and
/// keys parameters match the expected values from the claim record.
fn verify_claim_transaction(
    tx_data: &serde_json::Value,
    expected_session_id: &str,
    expected_amount: u64,
    expected_keys: u64,
) -> Result<(), String> {
    // Check 'to' address matches vault
    let to_address = tx_data
        .get("to")
        .and_then(|v| v.as_str())
        .ok_or_else(|| "Transaction missing 'to' field".to_string())?;

    if !to_address.eq_ignore_ascii_case(crate::config::VAULT_CONTRACT_ADDRESS) {
        return Err(format!(
            "Transaction 'to' address {} does not match vault {}",
            to_address,
            crate::config::VAULT_CONTRACT_ADDRESS
        ));
    }

    // Parse and verify the ABI-encoded claim parameters
    let parsed = parse_claim_input(tx_data)?;

    // Verify sessionId
    let expected_hex = expected_session_id
        .strip_prefix("0x")
        .unwrap_or(expected_session_id);
    if !parsed.session_id.eq_ignore_ascii_case(expected_hex) {
        return Err(format!(
            "Claim sessionId mismatch: tx has {}, expected {}",
            parsed.session_id, expected_hex
        ));
    }

    // Verify amount (compare in wei: expected_amount tokens * 10^18)
    let expected_wei = BigUint::from(expected_amount) * BigUint::from(10u64).pow(18);
    if parsed.amount_wei != expected_wei {
        return Err(format!(
            "Claim amount mismatch: tx has {} wei, expected {} wei",
            parsed.amount_wei, expected_wei
        ));
    }

    // Verify keys
    let expected_keys_big = BigUint::from(expected_keys);
    if parsed.keys != expected_keys_big {
        return Err(format!(
            "Claim keys mismatch: tx has {}, expected {}",
            parsed.keys, expected_keys_big
        ));
    }

    Ok(())
}

/// Parsed claim transaction data returned by `parse_claim_input`.
pub struct ParsedClaim {
    /// sessionId (bytes32) as hex string without 0x prefix
    pub session_id: String,
    /// amount in wei (uint256)
    pub amount_wei: BigUint,
    /// keys collected (uint256)
    pub keys: BigUint,
}

/// Parse a Vault.claim(bytes32,uint256,uint256,bytes) transaction's input data.
/// Verifies the function selector and decodes the ABI-encoded parameters.
///
/// ABI layout (standard encoding, `bytes` is dynamic):
///   [0..4]    function selector (4 bytes)
///   [4..36]   sessionId: bytes32  (32 bytes)
///   [36..68]  amount: uint256     (32 bytes)
///   [68..100] keys: uint256       (32 bytes)
///   [100..132] offset to `bytes signature` data (points past static area)
///   [132..164] length of signature bytes
///   [164..]   signature data (padded to 32-byte boundary)
///
/// We only extract the static params (sessionId, amount, keys) for verification.
/// The signature is verified on-chain by Vault.sol's ecrecover.
fn parse_claim_input(tx_data: &serde_json::Value) -> Result<ParsedClaim, String> {
    let input_hex = tx_data
        .get("input")
        .and_then(|v| v.as_str())
        .ok_or_else(|| "Transaction missing 'input' field".to_string())?;

    let input_clean = input_hex.strip_prefix("0x").unwrap_or(input_hex);

    // Minimum: 4-byte selector + 3 × 32-byte static params + 32-byte offset = 132 bytes = 264 hex chars
    if input_clean.len() < 264 {
        return Err(format!(
            "Input data too short for claim call: {} chars (need >= 264)",
            input_clean.len()
        ));
    }

    // 1. Verify function selector: claim(bytes32,uint256,uint256,bytes) = 0x95ace4b3
    let selector = &input_clean[0..8];
    if selector != CLAIM_SELECTOR {
        return Err(format!(
            "Wrong function selector: expected {} (claim), got {}",
            CLAIM_SELECTOR, selector
        ));
    }

    // 2. Decode sessionId from bytes 4..36 (first param, bytes32)
    let session_id_hex = &input_clean[8..72]; // 64 hex chars = 32 bytes

    // 3. Decode amount from bytes 36..68 (second param, uint256)
    let amount_hex = &input_clean[72..136]; // 64 hex chars = 32 bytes
    let amount_wei = BigUint::parse_bytes(amount_hex.as_bytes(), 16)
        .ok_or_else(|| format!("Failed to parse claim amount: {}", amount_hex))?;

    // 4. Decode keys from bytes 68..100 (third param, uint256)
    let keys_hex = &input_clean[136..200]; // 64 hex chars = 32 bytes
    let keys = BigUint::parse_bytes(keys_hex.as_bytes(), 16)
        .ok_or_else(|| format!("Failed to parse claim keys: {}", keys_hex))?;

    Ok(ParsedClaim {
        session_id: session_id_hex.to_string(),
        amount_wei,
        keys,
    })
}

/// Parsed fee transaction data returned by `parse_fee_input`.
pub struct ParsedFee {
    pub amount: u64,
    pub from: String,
}

/// Parse a Vault.payFee(uint256,bytes32) transaction's input data.
/// Verifies the tx targets the Vault contract, checks the function selector,
/// decodes the ABI-encoded amount parameter, and extracts the sender address.
fn parse_fee_input(tx_data: &serde_json::Value) -> Result<ParsedFee, String> {
    // 0. Extract tx.from (sender address) for caller validation
    let from_address = tx_data
        .get("from")
        .and_then(|v| v.as_str())
        .ok_or_else(|| "Transaction missing 'from' field".to_string())?
        .to_string();

    // 1. Verify tx.to matches the Vault contract address
    let to_address = tx_data
        .get("to")
        .and_then(|v| v.as_str())
        .ok_or_else(|| "Transaction missing 'to' field".to_string())?;

    if !to_address.eq_ignore_ascii_case(crate::config::VAULT_CONTRACT_ADDRESS) {
        return Err(format!(
            "Fee tx 'to' {} does not match vault {}",
            to_address,
            crate::config::VAULT_CONTRACT_ADDRESS
        ));
    }

    // 2. Parse the input data field (ERC-20 contract call, not tx.value)
    let input_hex = tx_data
        .get("input")
        .and_then(|v| v.as_str())
        .ok_or_else(|| "Transaction missing 'input' field".to_string())?;

    let input_clean = input_hex.strip_prefix("0x").unwrap_or(input_hex);

    // Minimum length: 4-byte selector + 32-byte amount + 32-byte sessionId = 68 bytes = 136 hex chars
    if input_clean.len() < 136 {
        return Err(format!(
            "Input data too short for fee call: {} chars",
            input_clean.len()
        ));
    }

    // 3. Verify function selector: payFee(uint256,bytes32) = 0xc6bbdafb
    let selector = &input_clean[0..8];
    if selector != PAY_FEE_SELECTOR {
        return Err(format!(
            "Wrong function selector: expected {} (payFee), got {}",
            PAY_FEE_SELECTOR, selector
        ));
    }

    // 4. Decode amount from bytes 4..36 (first ABI parameter, uint256)
    let amount_hex = &input_clean[8..72]; // 64 hex chars = 32 bytes
    let wei_amount = BigUint::parse_bytes(amount_hex.as_bytes(), 16)
        .ok_or_else(|| format!("Failed to parse fee amount: {}", amount_hex))?;

    // 5. Convert from wei to tokens (1 token = 10^18 wei)
    let one_token = BigUint::from(10u64).pow(18);
    let tokens = &wei_amount / &one_token;

    let amount = tokens
        .to_u64()
        .ok_or_else(|| format!("Fee amount too large for u64: {} wei", wei_amount))?;

    Ok(ParsedFee {
        amount,
        from: from_address,
    })
}

// ---------------------------------------------------------------------------
// Internal: Transaction receipt verification (typed binding)
// ---------------------------------------------------------------------------

/// Verify a transaction receipt shows success (status 0x1).
/// Uses the typed `eth_get_transaction_receipt` method.
async fn verify_transaction_receipt(tx_hash: &str) -> Result<(), String> {
    let canister = evm_rpc_canister()?;

    let result = canister
        .eth_get_transaction_receipt(
            avalanche_rpc_services(),
            default_rpc_config(),
            tx_hash.to_string(),
            cycles_for_call(4096), // receipts are larger
        )
        .await?;

    match result.0 {
        MultiGetTransactionReceiptResult::Consistent(receipt_result) => match receipt_result {
            GetTransactionReceiptResult::Ok(maybe_receipt) => {
                match maybe_receipt {
                    Some(receipt) => {
                        // Check status field — Nat "1" means success
                        let status_nat = receipt
                            .status
                            .ok_or_else(|| "Receipt has no status field".to_string())?;
                        let status_val: u64 = status_nat
                            .0
                            .try_into()
                            .map_err(|_| "Receipt status too large".to_string())?;
                        if status_val != 1 {
                            return Err("Transaction reverted on-chain (status != 0x1)".to_string());
                        }
                        Ok(())
                    }
                    None => Err("Transaction receipt not found (tx may be pending)".to_string()),
                }
            }
            GetTransactionReceiptResult::Err(e) => Err(format!("Receipt RPC error: {:?}", e)),
        },
        MultiGetTransactionReceiptResult::Inconsistent(results) => Err(format!(
            "Inconsistent receipt results from {} providers",
            results.len()
        )),
    }
}

// ---------------------------------------------------------------------------
// Internal: Withdrawal transaction building
// ---------------------------------------------------------------------------

/// Build an ERC-20 transfer withdrawal transaction, sign it with threshold ECDSA,
/// and return the signed tx as a hex string.
///
/// Targets the TRESR token contract with `transfer(address,uint256)` calldata.
/// Native AVAX value is 0 — this is a token transfer, not a native transfer.
async fn build_withdrawal_tx(to_address: &str, amount: u64) -> Result<String, String> {
    // Step 1: Get our Ethereum address from ECDSA public key
    let from_address = get_eth_address().await?;

    // Step 2: Get the current nonce for our address
    let nonce = get_transaction_count(&from_address).await?;

    // Step 3: Build ERC-20 transfer(address,uint256) calldata
    let recipient_hex = to_address.strip_prefix("0x").unwrap_or(to_address);
    let recipient_bytes =
        hex::decode(recipient_hex).map_err(|e| format!("Invalid recipient address: {}", e))?;
    if recipient_bytes.len() != 20 {
        return Err(format!(
            "Recipient address must be 20 bytes, got {}",
            recipient_bytes.len()
        ));
    }
    let amount_wei = BigUint::from(amount) * BigUint::from(10u64).pow(18);
    let amount_be = amount_wei.to_bytes_be();

    // ABI encode: selector (4) + address padded to 32 + uint256 padded to 32 = 68 bytes
    let mut calldata = Vec::with_capacity(68);
    calldata.extend_from_slice(&TRANSFER_SELECTOR); // 4 bytes
    calldata.extend_from_slice(&[0u8; 12]); // left-pad address to 32 bytes
    calldata.extend_from_slice(&recipient_bytes); // 20 bytes
    let pad_len = 32usize.saturating_sub(amount_be.len());
    calldata.extend_from_slice(&vec![0u8; pad_len]); // left-pad amount to 32 bytes
    calldata.extend_from_slice(&amount_be);

    let calldata_hex = format!("0x{}", hex::encode(&calldata));

    // Step 4: Parse token contract address as the RLP `to` field
    let token_addr_clean = crate::config::TRESR_TOKEN_CONTRACT
        .strip_prefix("0x")
        .unwrap_or(crate::config::TRESR_TOKEN_CONTRACT);
    let token_bytes = hex::decode(token_addr_clean)
        .map_err(|e| format!("Invalid token contract address: {}", e))?;

    // Step 5: Get dynamic gas parameters with fallback to defaults
    let gas_price = get_gas_price().await.unwrap_or(DEFAULT_GAS_PRICE);
    let gas_limit = estimate_gas(
        &from_address,
        crate::config::TRESR_TOKEN_CONTRACT,
        &calldata_hex,
        None, // value is 0 for ERC-20 transfer
    )
    .await
    .map(|g| g * 110 / 100) // 10% buffer
    .unwrap_or(65_000); // ERC-20 transfers typically need ~65k gas

    // Step 6: Build the unsigned transaction for signing (EIP-155)
    let mut rlp_stream = RlpStream::new();
    rlp_stream.begin_list(9);
    rlp_stream.append(&nonce);
    rlp_stream.append(&gas_price);
    rlp_stream.append(&gas_limit);
    rlp_stream.append(&token_bytes); // to = token contract
    rlp_stream.append(&0u64); // value = 0 (no native AVAX)
    rlp_stream.append(&calldata); // data = transfer() calldata
    rlp_stream.append(&crate::config::AVALANCHE_CHAIN_ID);
    rlp_stream.append(&0u8); // r = 0 for unsigned tx
    rlp_stream.append(&0u8); // s = 0 for unsigned tx

    let unsigned_tx_bytes = rlp_stream.out().to_vec();

    // Step 7: Hash the transaction with keccak256
    let tx_hash = keccak256(&unsigned_tx_bytes);

    // Step 8: Sign the transaction hash with threshold ECDSA
    let signature = sign_with_ecdsa(&tx_hash).await?;

    // Step 9: Extract r, s, v from signature (async — determines correct recovery ID)
    let (r, s, v) =
        extract_signature_components(&signature, &tx_hash, crate::config::AVALANCHE_CHAIN_ID)
            .await?;

    // Step 10: Build the final signed transaction
    let mut signed_rlp = RlpStream::new();
    signed_rlp.begin_list(9);
    signed_rlp.append(&nonce);
    signed_rlp.append(&gas_price);
    signed_rlp.append(&gas_limit);
    signed_rlp.append(&token_bytes); // to = token contract
    signed_rlp.append(&0u64); // value = 0
    signed_rlp.append(&calldata); // data = transfer() calldata
    signed_rlp.append(&v);
    signed_rlp.append(&r);
    signed_rlp.append(&s);

    let signed_tx_bytes = signed_rlp.out().to_vec();

    // Step 11: Convert to hex string with 0x prefix
    Ok(format!("0x{}", hex::encode(signed_tx_bytes)))
}

// ---------------------------------------------------------------------------
// Public API: ECDSA key management
// ---------------------------------------------------------------------------

/// Get the Ethereum address derived from our ECDSA public key
pub async fn get_eth_address() -> Result<String, String> {
    let key_id = EcdsaKeyId {
        curve: EcdsaCurve::Secp256k1,
        name: ECDSA_KEY_NAME.to_string(),
    };

    let request = EcdsaPublicKeyArgs {
        canister_id: None,
        derivation_path: vec![],
        key_id: key_id.clone(),
    };

    let response = ecdsa_public_key(&request)
        .await
        .map_err(|e| format!("Failed to get ECDSA public key: {:?}", e))?;

    // The IC returns SEC1-encoded public keys which may be either:
    //   - Uncompressed (65 bytes): 0x04 || x || y
    //   - Compressed   (33 bytes): 0x02/0x03 || x
    // Use libsecp256k1 to parse either format and serialize to uncompressed.
    let public_key = &response.public_key;

    let parsed_key = if public_key.len() == 33 {
        libsecp256k1::PublicKey::parse_compressed(
            public_key
                .as_slice()
                .try_into()
                .map_err(|_| "Public key is not 33 bytes".to_string())?,
        )
        .map_err(|e| format!("Failed to parse compressed public key: {:?}", e))?
    } else if public_key.len() == 65 {
        libsecp256k1::PublicKey::parse(
            public_key
                .as_slice()
                .try_into()
                .map_err(|_| "Public key is not 65 bytes".to_string())?,
        )
        .map_err(|e| format!("Failed to parse uncompressed public key: {:?}", e))?
    } else {
        return Err(format!(
            "Unexpected public key length: {} (expected 33 or 65)",
            public_key.len()
        ));
    };

    // Serialize to uncompressed form: 0x04 || x || y (65 bytes)
    let uncompressed = parsed_key.serialize();

    // For Ethereum address: keccak256(x || y) and take last 20 bytes
    // Skip the 0x04 prefix byte
    let hash = keccak256(&uncompressed[1..]);
    let address_bytes = &hash[12..];
    Ok(format!("0x{}", hex::encode(address_bytes)))
}

// ---------------------------------------------------------------------------
// Internal: Transaction count / nonce (typed binding)
// ---------------------------------------------------------------------------

/// Get transaction count (nonce) for an Ethereum address.
/// Uses the typed `eth_get_transaction_count` method.
async fn get_transaction_count(address: &str) -> Result<u64, String> {
    let canister = evm_rpc_canister()?;

    let args = GetTransactionCountArgs {
        address: address.to_string(),
        block: BlockTag::Latest,
    };

    let result = canister
        .eth_get_transaction_count(
            avalanche_rpc_services(),
            default_rpc_config(),
            args,
            cycles_for_call(256), // nonce is a small response
        )
        .await?;

    match result.0 {
        MultiGetTransactionCountResult::Consistent(count_result) => match count_result {
            GetTransactionCountResult::Ok(count) => {
                let nonce: u64 = count
                    .0
                    .try_into()
                    .map_err(|_| "Nonce too large for u64".to_string())?;
                Ok(nonce)
            }
            GetTransactionCountResult::Err(e) => Err(format!("Nonce RPC error: {:?}", e)),
        },
        MultiGetTransactionCountResult::Inconsistent(results) => Err(format!(
            "Inconsistent nonce results from {} providers",
            results.len()
        )),
    }
}

// ---------------------------------------------------------------------------
// Internal: ECDSA signing
// ---------------------------------------------------------------------------

/// Sign a message hash with threshold ECDSA
pub async fn sign_with_ecdsa(message_hash: &[u8]) -> Result<Vec<u8>, String> {
    let key_id = EcdsaKeyId {
        curve: EcdsaCurve::Secp256k1,
        name: ECDSA_KEY_NAME.to_string(),
    };

    let request = SignWithEcdsaArgs {
        message_hash: message_hash.to_vec(),
        derivation_path: vec![],
        key_id,
    };

    let response = mgmt_sign_with_ecdsa(&request)
        .await
        .map_err(|e| format!("Failed to sign with ECDSA: {:?}", e))?;

    Ok(response.signature)
}

/// Determine the correct ECDSA recovery ID (0 or 1) by trying both and
/// comparing the recovered Ethereum address against the canister's address.
///
/// This is a shared helper used by both `extract_signature_components` (EIP-155
/// transactions) and `generate_claim_signature` (EIP-191 personal signatures).
pub async fn determine_recovery_id(signature: &[u8], message_hash: &[u8]) -> Result<u8, String> {
    if signature.len() != 64 {
        return Err(format!(
            "Invalid signature length: expected 64, got {}",
            signature.len()
        ));
    }
    if message_hash.len() != 32 {
        return Err(format!(
            "Invalid message hash length: expected 32, got {}",
            message_hash.len()
        ));
    }

    let canister_address = get_eth_address().await?;
    let canister_addr_lower = canister_address.trim_start_matches("0x").to_lowercase();

    let mut hash_arr = [0u8; 32];
    hash_arr.copy_from_slice(message_hash);
    let message = Message::parse(&hash_arr);
    let sig = Signature::parse_standard_slice(signature)
        .map_err(|e| format!("Invalid signature: {:?}", e))?;

    for id in 0u8..2u8 {
        let recid = RecoveryId::parse(id).map_err(|e| format!("Invalid recovery ID: {:?}", e))?;
        if let Ok(pubkey) = recover(&message, &sig, &recid) {
            let pubkey_serialized = pubkey.serialize();
            let recovered_addr = pubkey_to_eth_address(&pubkey_serialized[1..65]);
            if recovered_addr == canister_addr_lower {
                return Ok(id);
            }
        }
    }

    Err("Could not determine recovery ID: neither 0 nor 1 matched the canister address".to_string())
}

/// Derive a lowercase hex Ethereum address (without 0x prefix) from raw
/// uncompressed public key bytes (64 bytes, without the 0x04 prefix).
fn pubkey_to_eth_address(pubkey_bytes: &[u8]) -> String {
    let hash = keccak256(pubkey_bytes);
    hex::encode(&hash[12..])
}

/// Extract r, s, v components from ECDSA signature for Ethereum (EIP-155).
///
/// Determines the correct recovery ID by trying both 0 and 1 and matching
/// against the canister's Ethereum address.
async fn extract_signature_components(
    signature: &[u8],
    message_hash: &[u8],
    chain_id: u64,
) -> Result<(Vec<u8>, Vec<u8>, u64), String> {
    // ECDSA signature is 64 bytes: r (32 bytes) || s (32 bytes)
    if signature.len() != 64 {
        return Err(format!(
            "Invalid signature length: expected 64, got {}",
            signature.len()
        ));
    }

    let r = signature[0..32].to_vec();
    let s = signature[32..64].to_vec();

    // Determine correct recovery ID (ticket #268)
    let recovery_id = determine_recovery_id(signature, message_hash).await?;

    // EIP-155: v = chain_id * 2 + 35 + recovery_id
    let v = chain_id * 2 + 35 + recovery_id as u64;

    Ok((r, s, v))
}

// ---------------------------------------------------------------------------
// Public API: Token balance (typed binding — eth_call)
// ---------------------------------------------------------------------------

/// Get the ERC-20 token balance for a wallet address.
/// Uses the typed `eth_call` method.
pub async fn get_token_balance(wallet_address: &str) -> Result<u64, String> {
    // Anvil mock: return fake balance in local dev
    if crate::config::NETWORK_NAME == "anvil" {
        crate::logging::log_debug(
            "EvmRpc",
            &format!("ANVIL_MOCK: get_token_balance for {}", wallet_address),
        );
        return Ok(1000);
    }

    let canister = evm_rpc_canister()?;

    // ABI encode balanceOf(address): selector 0x70a08231 + 32-byte padded address
    let addr_hex = wallet_address.strip_prefix("0x").unwrap_or(wallet_address);
    let data = format!("0x70a08231{:0>64}", addr_hex);

    let call_args = CallArgs {
        transaction: TransactionRequest {
            to: Some(crate::config::TRESR_TOKEN_CONTRACT.to_string()),
            input: Some(data),
            ..TransactionRequest::default()
        },
        block: Some(BlockTag::Latest),
    };

    let result = canister
        .eth_call(
            avalanche_rpc_services(),
            default_rpc_config(),
            call_args,
            cycles_for_call(256), // balance is a small response
        )
        .await?;

    match result.0 {
        MultiCallResult::Consistent(call_result) => match call_result {
            EvmCallResult::Ok(hex_result) => parse_balance_hex(&hex_result),
            EvmCallResult::Err(e) => Err(format!("eth_call error: {:?}", e)),
        },
        MultiCallResult::Inconsistent(results) => Err(format!(
            "Inconsistent eth_call results from {} providers",
            results.len()
        )),
    }
}

/// Parse a hex-encoded uint256 balance result into token units (divide by 10^18).
fn parse_balance_hex(hex_result: &str) -> Result<u64, String> {
    let hex_str = hex_result.trim().trim_matches('"');
    let hex_clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    if hex_clean.is_empty() || hex_clean.chars().all(|c| c == '0') {
        return Ok(0);
    }

    let wei = BigUint::parse_bytes(hex_clean.as_bytes(), 16)
        .ok_or_else(|| format!("Failed to parse balance hex: {}", hex_clean))?;
    let one_token = BigUint::from(10u64).pow(18);
    let tokens = &wei / &one_token;
    tokens
        .to_u64()
        .ok_or_else(|| "Balance too large for u64".to_string())
}

// ---------------------------------------------------------------------------
// Public API: Gas price (raw JSON-RPC — no typed binding)
// ---------------------------------------------------------------------------

/// Get current gas price from the network.
/// Uses raw JSON-RPC via `request` (no typed binding for eth_gasPrice).
pub async fn get_gas_price() -> Result<u64, String> {
    if crate::config::NETWORK_NAME == "anvil" {
        return Ok(DEFAULT_GAS_PRICE);
    }

    let body = json_rpc_request("eth_gasPrice", "[]").await?;
    let result = parse_json_rpc_result(&body)?;

    let hex_str = result
        .as_str()
        .ok_or_else(|| "eth_gasPrice result is not a string".to_string())?;
    let clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    u64::from_str_radix(clean, 16).map_err(|e| format!("Failed to parse gas price: {}", e))
}

// ---------------------------------------------------------------------------
// Public API: Gas estimation (raw JSON-RPC — no typed binding)
// ---------------------------------------------------------------------------

/// Estimate gas for a transaction.
/// Uses raw JSON-RPC via `request` (no typed binding for eth_estimateGas).
pub async fn estimate_gas(
    from: &str,
    to: &str,
    data: &str,
    value: Option<&str>,
) -> Result<u64, String> {
    if crate::config::NETWORK_NAME == "anvil" {
        return Ok(65_000);
    }

    let mut tx = serde_json::json!({ "from": from, "to": to, "data": data });
    if let Some(v) = value {
        tx["value"] = serde_json::json!(v);
    }

    let params =
        serde_json::to_string(&vec![tx]).map_err(|e| format!("JSON serialization error: {}", e))?;

    let body = json_rpc_request("eth_estimateGas", &params).await?;
    let result = parse_json_rpc_result(&body)?;

    let hex_str = result
        .as_str()
        .ok_or_else(|| "eth_estimateGas result is not a string".to_string())?;
    let clean = hex_str.strip_prefix("0x").unwrap_or(hex_str);
    u64::from_str_radix(clean, 16).map_err(|e| format!("Failed to parse gas estimate: {}", e))
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

/// Compute keccak256 hash of data
pub fn keccak256(data: &[u8]) -> Vec<u8> {
    let mut hasher = Keccak::v256();
    let mut output = [0u8; 32];
    hasher.update(data);
    hasher.finalize(&mut output);
    output.to_vec()
}
