//! Build script — reads config/tresr.yaml and generates Rust constants.
//!
//! Generated file: `$OUT_DIR/generated_config.rs`
//! Network selection: `SATELLITE_NETWORK` env var (default: "mainnet")

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

// Minimal structs — only the fields the satellite needs.

#[derive(Deserialize)]
struct Config {
    server: Server,
    client: Client,
}

#[derive(Deserialize)]
struct Server {
    anti_cheat: AntiCheat,
}

#[derive(Deserialize)]
struct AntiCheat {
    ban_durations_hours: Vec<u64>,
    permanent_after_offence: u64,
}

#[derive(Deserialize)]
struct Client {
    blockchain: Blockchain,
    gameplay: Gameplay,
}

#[derive(Deserialize)]
struct Gameplay {
    max_keys: u64,
}

#[derive(Deserialize)]
struct Blockchain {
    avalanche: AvalancheNetworks,
    icp: Icp,
}

#[derive(Deserialize)]
struct AvalancheNetworks {
    anvil: AvalancheNetwork,
    testnet: AvalancheNetwork,
    mainnet: AvalancheNetwork,
}

#[derive(Deserialize)]
struct AvalancheNetwork {
    chain_id: u64,
    vault_contract: String,
    tresr_token_contract: String,
}

#[derive(Deserialize)]
struct Icp {
    evm_rpc_canister_id: String,
}

fn main() {
    // Re-run when config changes
    println!("cargo::rerun-if-changed=../../config/tresr.yaml");
    println!("cargo::rerun-if-env-changed=SATELLITE_NETWORK");

    // Read config
    let yaml_path = Path::new("../../config/tresr.yaml");
    let yaml_str = fs::read_to_string(yaml_path).unwrap_or_else(|e| {
        panic!(
            "Failed to read config/tresr.yaml at {}: {}",
            yaml_path.display(),
            e
        )
    });

    let config: Config = serde_yaml::from_str(&yaml_str).unwrap_or_else(|e| {
        panic!("Failed to parse tresr.yaml: {}", e);
    });

    // Select network (default: mainnet)
    let network = env::var("SATELLITE_NETWORK").unwrap_or_else(|_| "mainnet".to_string());
    let chain = match network.as_str() {
        "anvil" => &config.client.blockchain.avalanche.anvil,
        "testnet" => &config.client.blockchain.avalanche.testnet,
        "mainnet" => &config.client.blockchain.avalanche.mainnet,
        other => panic!("Unknown SATELLITE_NETWORK: '{}'. Use anvil, testnet, or mainnet.", other),
    };

    // Format ban durations as Rust array literal
    let ban_durations = config
        .server
        .anti_cheat
        .ban_durations_hours
        .iter()
        .map(|d| d.to_string())
        .collect::<Vec<_>>()
        .join(", ");

    // Generate Rust constants
    let ecdsa_key_name = match network.as_str() {
        "mainnet" => "key_1",
        _ => "test_key_1", // anvil + testnet use the IC test key
    };

    let generated = format!(
        r#"// Auto-generated by build.rs from config/tresr.yaml — DO NOT EDIT
// Network: {network}

/// Ban durations in hours (from server.anti_cheat.ban_durations_hours)
pub const BAN_DURATIONS_HOURS: &[u64] = &[{ban_durations}];

/// Offence count at which ban becomes permanent (from server.anti_cheat.permanent_after_offence)
pub const PERMANENT_AFTER_OFFENCE: u64 = {permanent};

/// Maximum keys a player can collect per session (from client.gameplay.max_keys)
pub const MAX_KEYS_COLLECTED: u64 = {max_keys};

/// EVM RPC canister ID on the Internet Computer (from client.blockchain.icp.evm_rpc_canister_id)
pub const EVM_RPC_CANISTER_ID: &str = "{evm_rpc_canister_id}";

/// Avalanche chain ID for the selected network (from client.blockchain.avalanche.{network}.chain_id)
pub const AVALANCHE_CHAIN_ID: u64 = {chain_id};

/// Vault contract address on Avalanche (from client.blockchain.avalanche.{network}.vault_contract)
pub const VAULT_CONTRACT_ADDRESS: &str = "{vault_contract}";

/// TRESR token contract address on Avalanche (from client.blockchain.avalanche.{network}.tresr_token_contract)
pub const TRESR_TOKEN_CONTRACT: &str = "{token_contract}";

/// Network name for conditional logic (anvil/testnet/mainnet)
pub const NETWORK_NAME: &str = "{network}";

/// ECDSA key name for IC threshold signing (test_key_1 for dev/staging, key_1 for production)
pub const ECDSA_KEY_NAME: &str = "{ecdsa_key_name}";
"#,
        network = network,
        ban_durations = ban_durations,
        permanent = config.server.anti_cheat.permanent_after_offence,
        max_keys = config.client.gameplay.max_keys,
        evm_rpc_canister_id = config.client.blockchain.icp.evm_rpc_canister_id,
        chain_id = chain.chain_id,
        vault_contract = chain.vault_contract,
        token_contract = chain.tresr_token_contract,
        ecdsa_key_name = ecdsa_key_name,
    );

    // Write to OUT_DIR
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("generated_config.rs");
    fs::write(&dest_path, generated).unwrap_or_else(|e| {
        panic!("Failed to write {}: {}", dest_path.display(), e);
    });
}
