---
description: |
  Look here degen, this is just a fun, unofficial game I whipped up for the TRESR community.

  It's kind of like fanfic but with crypto twists and pixels.

  _No official ties to the TRESR project_ (you know, the ones slinging those killer t-shirts over at tresr.com).

  Bugs might creep in, or things could glitch out, maybe even feel like a mini rug pull if the code gets funky (crypto stuff's wild like that, right?).

  But that's all on me – the TRESR folks aren't to blame; they're the pros laying the groundwork we all love.

  This was put together with a ton of heart ❤️, some wild ideas, and mad respect for the TRESR community.

  Disclaimer out of the way, let's hit the credits!

  This whole thing's built on the work of some absolute legends; without 'em, we'd be nowhere in this crypto playground.

  Big ups to these folks;
coders:
  - name: MAHDTech
    role: Degenerate Programmer
    description: Platform Engineer moonlighting as a game dev.
  - name: Phantom
    role: Opinion Giver
    description: MAHDTech's eldest son, giver of opinions and selector of AI Art/Music.
  - name: Remminator
    role: Consumer of Snacks
    description: MAHDTech's youngest son and master of eating snacks.
components:
  - name: Astro
  - name: Avalanche Network
  - name: DaisyUI
  - name: Internet Computer Protocol
  - name: Juno
  - name: Phaser 3
assets:
  - type: audio
    subtype: sfx
    provider: Eleven Labs
  - type: audio
    subtype: narration
    provider: Eleven Labs
  - type: audio
    subtype: music
    provider: Suno
  - type: art
    subtype: character
    provider: Google Gemini Nano Banana
  - type: art
    subtype: backgrounds
    provider: Google Gemini Nano Banana
