// TypeScript declarations for the custom Satellite extension API.
// Generated by @icp-sdk/bindgen from satellite_extension.did.
// Re-run via: npx @icp-sdk/bindgen (if/when upgrading)
export * from './satellite.did';
export * from './satellite.api';
