/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Nat8)),
    'Err' : IDL.Text,
  });

  return IDL.Service({
    'claim_authorize' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };