/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Result = { 'Ok' : [bigint, Uint8Array] } |
  { 'Err' : string };
export type Result_1 = { 'Ok' : string } |
  { 'Err' : string };
export interface _SERVICE {
  /**
   * Authorize a claim with replay verification
   */
  'claim_authorize' : ActorMethod<[string, bigint, string, Uint8Array], Result>,
  /**
   * Returns the satellite's Public Ethereum address derived from its threshold ECDSA key.
   * This is the oracle address used for on-chain signature verification.
   */
  'get_oracle_address' : ActorMethod<[], Result_1>,
}
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];