/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({
    'Ok' : IDL.Tuple(IDL.Nat, IDL.Vec(IDL.Nat8)),
    'Err' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'Ok' : IDL.Null, 'Err' : IDL.Text });
  const ErrorRecord = IDL.Record({
    'resolved' : IDL.Bool,
    'component' : IDL.Text,
    'principal' : IDL.Text,
    'timestamp_ms' : IDL.Nat64,
    'raw_error' : IDL.Text,
    'message' : IDL.Text,
    'environment' : IDL.Text,
    'error_id' : IDL.Text,
  });
  const Result_2 = IDL.Variant({
    'Ok' : IDL.Vec(ErrorRecord),
    'Err' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'Ok' : IDL.Text, 'Err' : IDL.Text });
  const ErrorPayload = IDL.Record({
    'component' : IDL.Text,
    'raw_error' : IDL.Text,
    'message' : IDL.Text,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformArgs = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  
  return IDL.Service({
    'claim_authorize' : IDL.Func(
        [IDL.Text, IDL.Nat64, IDL.Text, IDL.Vec(IDL.Nat8)],
        [Result],
        [],
      ),
    'delete_errors' : IDL.Func([IDL.Vec(IDL.Text)], [Result_1], []),
    'get_config_hash' : IDL.Func([], [IDL.Text], ['query']),
    'get_errors' : IDL.Func([], [Result_2], []),
    'get_oracle_address' : IDL.Func([], [Result_3], []),
    'report_error' : IDL.Func([ErrorPayload], [Result_3], []),
    'resolve_error' : IDL.Func([IDL.Text, IDL.Bool], [Result_1], []),
    'strip_http_headers' : IDL.Func(
        [TransformArgs],
        [HttpRequestResult],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };