// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type {_SERVICE as SatelliteActor, Result, Result_1} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

export const claimAuthorize = async (value0: string, value1: bigint, value2: string, value3: Uint8Array): Promise<Result> => {
	const {claim_authorize} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await claim_authorize(value0, value1, value2, value3);
}

export const getOracleAddress = async (): Promise<Result_1> => {
	const {get_oracle_address} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_oracle_address();
}