// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

import type {_SERVICE as SatelliteActor, ErrorPayload, ErrorRecord, Result, Result_1, Result_2, Result_3} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

export const claimAuthorize = async (value0: string, value1: bigint, value2: string, value3: Uint8Array): Promise<Result> => {
	const {claim_authorize} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await claim_authorize(value0, value1, value2, value3);
}

// MANUAL PATCH: Juno CLI codegen bug — `vec text` args are emitted as bare `Array`
// instead of `Array<string>`. Re-apply this fix after every `juno functions build`
// until the upstream issue is resolved. Reported in Juno Discord (Mar 2026).
export const deleteErrors = async (value0: Array<string>): Promise<Result_1> => {
const {delete_errors} = await getSatelliteExtendedActor<SatelliteActor>({
idlFactory
});

    return await delete_errors(value0);

}

export const getErrors = async (): Promise<Result_2> => {
	const {get_errors} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_errors();
}

export const getOracleAddress = async (): Promise<Result_3> => {
	const {get_oracle_address} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_oracle_address();
}

export const reportError = async (value0: ErrorPayload): Promise<Result_3> => {
	const {report_error} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await report_error(value0);
}