// This file was automatically generated by the Juno CLI.
// Any modifications may be overwritten.

/* eslint-disable */
/* prettier-ignore */

import type {_SERVICE as SatelliteActor, ErrorPayload, ErrorRecord, Result, Result_1, Result_2, Result_3} from './satellite.did';
import type { Principal } from '@icp-sdk/core/principal';
// @ts-expect-error - generated JS file without type declarations
import {idlFactory} from './satellite.factory.did.js';
import {getSatelliteExtendedActor} from '@junobuild/core';

const claimAuthorize = async (value0: string, value1: bigint, value2: string, value3: Uint8Array): Promise<Result> => {
	const {claim_authorize} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await claim_authorize(value0, value1, value2, value3);
}

const deleteErrors = async (value0: Array<string>): Promise<Result_1> => {
	const {delete_errors} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await delete_errors(value0);
}

const getConfigHash = async (): Promise<string> => {
	const {get_config_hash} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_config_hash();
}

const getErrors = async (): Promise<Result_2> => {
	const {get_errors} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_errors();
}

const getOracleAddress = async (): Promise<Result_3> => {
	const {get_oracle_address} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await get_oracle_address();
}

const reportError = async (value0: ErrorPayload): Promise<Result_3> => {
	const {report_error} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await report_error(value0);
}

const resolveError = async (value0: string, value1: boolean): Promise<Result_1> => {
	const {resolve_error} = await getSatelliteExtendedActor<SatelliteActor>({
		idlFactory
	});

	return await resolve_error(value0, value1);
}

export const functions = {
	claimAuthorize,
	deleteErrors,
	getConfigHash,
	getErrors,
	getOracleAddress,
	reportError,
	resolveError
};