[profile.default]

src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.27'

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "forge-std/=lib/forge-std/src/"
]

[profile.ci]
# Inherits [profile.default]. Used by ci-foundry.yaml for PR checks.
verbosity = 3

[profile.testnet]
# Inherits [profile.default]. Used by cd-foundry-testnet.yaml.
verbosity = 3

[profile.mainnet]
# Inherits [profile.default]. Used by cd-foundry-mainnet.yaml.
verbosity = 2

[rpc_endpoints]

fuji = "https://api.avax-test.network/ext/bc/C/rpc"
mainnet = "https://api.avax.network/ext/bc/C/rpc"

[etherscan]

fuji = { key = "${SNOWTRACE_API_KEY}", url = "https://api-testnet.snowtrace.io/api" }
mainnet = { key = "${SNOWTRACE_API_KEY}", url = "https://api.snowtrace.io/api" }
