// AUTO-GENERATED by bin/client-config.ts — DO NOT EDIT

export const SERVER_CONFIG_HASH = "7cbb74b557fed28e0d0b305403f73cc269aa0c31a73c6f1cca78eee7af4c928b" as const;

export const SERVER_CRITICAL_VALUES = {
  "entities": {
    "player": {
      "health": 1000,
      "damage": 25,
      "speed": 300,
      "jump_force": 25,
      "knockback": {
        "force": 200,
        "stun_ms": 300
      },
      "hitbox": {
        "radius": 20,
        "offsetX": 236,
        "offsetY": 472
      },
      "combat": {
        "reach": 80,
        "attack_range": 80,
        "hit_stop_ms": 50
      },
      "super": {
        "damage": 250,
        "splash_damage": 250,
        "splash_radius": 100,
        "speed": 500,
        "max_range": 1000,
        "charge_per_kill": 10,
        "max_charge": 100,
        "max_projectiles": 3,
        "hitbox": {
          "width": 30,
          "height": 50,
          "hit_radius": 40,
          "depth_threshold": 60,
          "fire_offset": 40,
          "offscreen_margin": 50
        },
        "effects": {
          "shake_duration": 200,
          "shake_intensity": 0.02,
          "explosion_initial_radius": 10,
          "explosion_expand_duration": 300
        }
      },
      "health_bar": {
        "width": 50,
        "height": 6,
        "offset_y": -5
      },
      "effects": {
        "attack_shake_duration": 100,
        "attack_shake_intensity": 0.01,
        "victory_flash_duration": 500
      },
      "spawn": {
        "x_ratio": 0.039,
        "y_ratio": 0.903
      },
      "lives": 1,
      "respawn": {
        "invincibility_ms": 3000,
        "blink_interval_ms": 100,
        "delay_ms": 1000
      },
      "input": {
        "gamepad_deadzone": 0.2,
        "touch": {
          "joystick_radius": 50,
          "joystick_deadzone": 0.15
        }
      }
    },
    "enemy": {
      "health": 100,
      "damage": 10,
      "speed": 150,
      "flee_speed_mult": 1.5,
      "flee_margin_px": 50,
      "offscreen_kill_distance_px": 100,
      "walk_in_boundary_margin_px": 5,
      "knockback": {
        "force": 300,
        "stun_ms": 200
      },
      "hitbox": {
        "radius": 18,
        "offsetX": 238,
        "offsetY": 476
      },
      "combat": {
        "attack_range": 80,
        "depth_threshold": 40,
        "attack_check_ms": 500
      },
      "ai": {
        "weights": {
          "cautious": 10,
          "direct": 20,
          "erratic": 20,
          "flanker": 20,
          "passive": 10,
          "retardio": 10,
          "swarm": 10
        },
        "cautious": {
          "speed_mult": 0.7,
          "preferred_distance": 250,
          "group_radius": 200,
          "pack_threshold": 4,
          "charge_speed_mult": 1.3,
          "strafe_speed_mult": 0.9,
          "strafe_switch_time": 2,
          "check_frame_interval": 10
        },
        "direct": {},
        "erratic": {
          "speed_mult": 1.2,
          "zigzag_frequency": 1.5,
          "zigzag_amplitude": 1.5,
          "jitter_x": 80,
          "jitter_y": 40
        },
        "flanker": {
          "speed_mult": 1.1,
          "offset": 200,
          "switch_time": 3,
          "orbit_time": 2,
          "lunge_speed_mult": 2.5,
          "lunge_duration": 0.3,
          "recovery_time": 0.8
        },
        "passive": {
          "speed_mult": 0.5,
          "provoked_speed_mult": 1.3,
          "hp_mult": 1.5
        },
        "retardio": {
          "speed_mult": 1.1,
          "jitter_time": 0.3,
          "retarget_time": 4,
          "attack_damage": 10,
          "attack_cooldown_s": 0.5,
          "rage_tint": 16711680
        },
        "swarm": {
          "speed_mult": 1,
          "group_radius": 150,
          "speed_bonus_per_ally": 0.15,
          "max_speed_mult": 2,
          "rush_threshold": 3,
          "rush_tint": 65416,
          "check_frame_interval": 10
        }
      },
      "health_bar": {
        "width": 30,
        "height": 4,
        "offset_y": -5
      },
      "animations": {
        "death_delay": 500
      },
      "spawner": {
        "pool_size": 50,
        "delay_ms": 2500,
        "buffer_distance": 50,
        "director": {
          "burst_chance": 0.15,
          "burst_count_min": 3,
          "burst_count_max": 7,
          "burst_delay_ms": 300,
          "breather_chance": 0.2,
          "breather_duration_ms": 5000,
          "limo_chance": 0.05,
          "limo_count": 5
        }
      },
      "loot": {
        "health": {
          "drop_chance": 0.25,
          "heal_amount": 25,
          "variants": 5
        },
        "powerup": {
          "drop_chance": 0.1,
          "variants": 5
        },
        "hitbox": {
          "width": 400,
          "height": 400
        },
        "pool_size": 20,
        "bob_distance": 8,
        "bob_duration": 600,
        "despawn_ms": 8000
      }
    },
    "boss": {
      "health": 50,
      "damage": 25,
      "speed": 150,
      "knockback": {
        "force": 50,
        "stun_ms": 100
      },
      "hitbox": {
        "radius": 20,
        "offsetX": 236,
        "offsetY": 472
      },
      "combat": {
        "attack_range": 60,
        "contact_depth_threshold": 60
      },
      "descent": {
        "speed": 3,
        "start_y": -100,
        "threshold_ratio": 0.903
      },
      "phases": {
        "enrage_threshold": 0.5,
        "phase2_speed_mult": 2,
        "phase2_damage_mult": 2,
        "enrage_tint": 16711680
      },
      "attacks": {
        "ground_pound": {
          "damage": 15,
          "radius": 120,
          "windup_ms": 800,
          "cooldown_ms": 5000
        },
        "charge": {
          "speed_mult": 4,
          "damage": 20,
          "duration_ms": 1000,
          "cooldown_ms": 7000
        },
        "summon": {
          "count": 3,
          "cooldown_ms": 10000
        }
      },
      "attack_cooldown_ms": 3000,
      "charge_range_mult": 2,
      "summon_pause_s": 0.5,
      "defeated_alpha": 0.5,
      "enrage_flash_ms": 200,
      "ground_pound_effects": {
        "shake_duration": 200,
        "shake_intensity": 0.01,
        "ring_initial_radius": 10,
        "ring_expand_duration": 400
      },
      "death_effects": {
        "shake_duration": 300,
        "shake_intensity": 0.025,
        "flash_duration": 200,
        "flash_r": 255,
        "flash_g": 200,
        "flash_b": 100
      },
      "health_bar": {
        "width": 80,
        "height": 8,
        "offset_y": -10
      },
      "animations": {
        "death_delay": 1000
      }
    },
    "key": {
      "speed": 80,
      "gravity": 0.04,
      "terminal_vz": 1.5,
      "drag": 0.12,
      "wind_frequency": 0.4,
      "bounce_threshold": 0.3,
      "oscillation": {
        "frequency": 3,
        "amplitude": 18
      },
      "bounce_damping": 0.2,
      "offscreen_kill_distance": 200,
      "animations": {
        "fade_duration": 500,
        "fade_delay": 3000
      },
      "spawner": {
        "pool_size": 20,
        "delay_ms": 2000,
        "start_z": 800,
        "x_margin": 100,
        "y_margin_top_ratio": 0.833,
        "y_margin_bottom_ratio": 0.035
      }
    },
    "bomb": {
      "damage": 50,
      "explosion_radius": 250,
      "hitbox": {
        "width": 25,
        "height": 25
      },
      "effects": {
        "shake_duration": 150,
        "shake_intensity": 0.015,
        "explosion_scale": 0.2,
        "explosion_duration": 300,
        "explosion_tint": 16737792,
        "explosion_alpha": 0.5
      },
      "spawner": {
        "pool_size": 10,
        "delay_ms": 5000,
        "start_z": 800,
        "x_margin": 100,
        "y_margin_top_ratio": 0.833,
        "y_margin_bottom_ratio": 0.035
      }
    },
    "chest": {
      "fallback_tint": 65280,
      "combat": {
        "interact_range": 100
      },
      "air_drop": {
        "delay_after_boss_ms": 1000,
        "landing_flash_color": 65416,
        "landing_flash_ms": 300,
        "landing_dust_color": 13412932,
        "landing_dust_radius": 80,
        "landing_dust_duration_ms": 400,
        "landing_shake_duration": 150,
        "landing_shake_intensity": 0.01
      }
    },
    "tresr_bot": {
      "health": 500,
      "damage": 50,
      "speed": 180,
      "air_drop": {
        "landing_flash_color": 65416,
        "landing_flash_ms": 500,
        "landing_dust_color": 8947848,
        "landing_dust_radius": 60,
        "landing_dust_duration_ms": 300,
        "landing_shake_duration": 100,
        "landing_shake_intensity": 0.005
      },
      "knockback": {
        "force": 120,
        "stun_ms": 200
      },
      "hitbox": {
        "radius": 13,
        "offsetX": 193,
        "offsetY": 361
      },
      "combat": {
        "attack_range": 80,
        "attack_cooldown_ms": 800,
        "target_switch_ms": 2000,
        "follow_distance": 80,
        "follow_speed_mult": 0.7
      },
      "lifetime": {
        "duration_ms": 30000,
        "fade_duration_ms": 1500,
        "spawn_flash_ms": 500
      },
      "special": {
        "cooldown_ms": 10000,
        "damage": 100,
        "radius": 120,
        "min_enemies": 3
      },
      "max_concurrent": 1,
      "max_drops_per_game": 5
    }
  },
  "scoring": {
    "key_collection": 100,
    "enemy_kill": 10,
    "boss_hit": 25,
    "super_hit": 25
  },
  "time_limit_seconds": 180,
  "max_keys": 150,
  "walkable_area": {
    "top_y_ratio": 0.85,
    "bottom_y_ratio": 1,
    "left_x_ratio": 0,
    "right_x_ratio": 1
  },
  "physics": {
    "fps": 60,
    "gravity": 0.75,
    "timestep": 0.01667,
    "game_speed": 1.5
  },
  "combat": {
    "enemy_damage_cooldown_ms": 500,
    "enemy_spawn_offscreen_px": 80,
    "boss_melee_range_bonus": 20,
    "projectile_hit_radius": 40
  },
  "audio": {
    "default_music_volume": 0.75,
    "default_sfx_volume": 0.5,
    "crossfade_duration_ms": 2000,
    "crossfade_step_ms": 50,
    "preference_save_debounce_ms": 2000,
    "sfx_variants": {
      "bot_attack": 2,
      "bot_spawn": 10,
      "bot_special": 1,
      "countdown": 2,
      "death": 4,
      "explosion": 3,
      "game_over": 3,
      "hurt": 6,
      "key_collect": 3,
      "open_treasure_chest": 3,
      "powerup_collect": 1,
      "punch": 5,
      "victory": 3
    },
    "sfx_volume_overrides": {
      "bot_attack": 1,
      "bot_spawn": 1,
      "bot_special": 1,
      "countdown": 1,
      "death": 1,
      "explosion": 1,
      "game_over": 1,
      "hurt": 1,
      "key_collect": 1,
      "open_treasure_chest": 1,
      "powerup_collect": 1,
      "punch": 1,
      "victory": 1
    }
  },
  "vault": {
    "max_score": 20000,
    "minimum_cap": 1000,
    "tiers": {
      "building": 10000,
      "sweet_spot": 50000,
      "fomo": 100000
    },
    "difficulty_multipliers": {
      "building": 1,
      "sweet_spot": 1.5,
      "fomo": 2,
      "legendary": 3
    },
    "payout_fixed": {
      "building": 500
    },
    "payout_percentages": {
      "sweet_spot": 10,
      "fomo": 25,
      "legendary": 50
    }
  },
  "fee_gate": {
    "transaction_timeout_ms": 300000
  },
  "difficulty_escalation": {
    "enabled": true,
    "interval_seconds": 60,
    "enemy_spawn_multiplier": 0.85,
    "bomb_spawn_multiplier": 0.9,
    "min_enemy_spawn_ms": 750,
    "min_bomb_spawn_ms": 2500
  }
} as const;
