// AUTO-GENERATED by bin/client-config.ts — DO NOT EDIT

export const SERVER_CONFIG_HASH = "c117f7817b6d8d897f40e1a949f856fec5af5014c504501256172bd94c1b654a" as const;

export const SERVER_CRITICAL_VALUES = {
  "entities": {
    "player": {
      "health": 1000,
      "damage": 25,
      "speed": 250,
      "jump_force": 12,
      "knockback": {
        "force": 200,
        "stun_ms": 300
      },
      "hitbox": {
        "radius": 40,
        "offsetX": 460,
        "offsetY": 920
      },
      "combat": {
        "reach": 80,
        "attack_range": 80,
        "hit_stop_ms": 50
      },
      "super": {
        "damage": 500,
        "splash_damage": 250,
        "splash_radius": 100,
        "speed": 500,
        "max_range": 1000,
        "charge_per_kill": 10,
        "max_charge": 100,
        "max_projectiles": 3,
        "hitbox": {
          "width": 30,
          "height": 50,
          "hit_radius": 40,
          "depth_threshold": 60,
          "fire_offset": 40,
          "offscreen_margin": 50
        },
        "effects": {
          "shake_duration": 200,
          "shake_intensity": 0.02,
          "explosion_initial_radius": 10,
          "explosion_expand_duration": 300
        }
      },
      "effects": {
        "attack_shake_duration": 100,
        "attack_shake_intensity": 0.01,
        "victory_flash_duration": 500
      },
      "spawn": {
        "x": 50,
        "y": 650
      },
      "lives": 1,
      "respawn": {
        "invincibility_ms": 3000,
        "blink_interval_ms": 100,
        "delay_ms": 1000
      },
      "input": {
        "gamepad_deadzone": 0.2,
        "touch": {
          "joystick_radius": 50,
          "joystick_deadzone": 0.15
        }
      }
    },
    "enemy": {
      "health": 100,
      "damage": 10,
      "speed": 100,
      "knockback": {
        "force": 300,
        "stun_ms": 200
      },
      "hitbox": {
        "radius": 35,
        "offsetX": 465,
        "offsetY": 930
      },
      "combat": {
        "attack_range": 80,
        "depth_threshold": 40,
        "attack_check_ms": 500
      },
      "ai": {
        "direct": {},
        "flanker": {
          "speed_mult": 1.1,
          "offset": 100,
          "switch_time": 3
        },
        "cautious": {
          "speed_mult": 0.7,
          "preferred_distance": 180,
          "group_radius": 200,
          "pack_threshold": 2,
          "charge_speed_mult": 1.3
        },
        "erratic": {
          "speed_mult": 1.2,
          "update_time": 0.5,
          "jitter_x": 150,
          "jitter_y": 100
        },
        "swarm": {
          "speed_mult": 1,
          "group_radius": 150,
          "speed_bonus_per_ally": 0.15,
          "max_speed_mult": 2
        },
        "passive": {
          "speed_mult": 0.5,
          "provoked_speed_mult": 1.3,
          "hp_mult": 1.5
        },
        "retardio": {
          "speed_mult": 1.1,
          "jitter_time": 0.3,
          "retarget_time": 4,
          "attack_damage": 10
        },
        "weights": {
          "cautious": 0,
          "direct": 100,
          "erratic": 0,
          "flanker": 0,
          "passive": 0,
          "retardio": 0,
          "swarm": 0
        }
      },
      "animations": {
        "death_delay": 500
      },
      "spawner": {
        "pool_size": 50,
        "delay_ms": 3000,
        "buffer_distance": 50
      },
      "loot": {
        "health": {
          "drop_chance": 0.25,
          "heal_amount": 25,
          "variants": 5
        },
        "powerup": {
          "drop_chance": 0.1,
          "variants": 5
        },
        "hitbox": {
          "width": 400,
          "height": 400
        },
        "pool_size": 20,
        "bob_distance": 8,
        "bob_duration": 600,
        "despawn_ms": 8000
      }
    },
    "boss": {
      "health": 1000,
      "damage": 25,
      "speed": 150,
      "knockback": {
        "force": 50,
        "stun_ms": 100
      },
      "hitbox": {
        "radius": 40,
        "offsetX": 460,
        "offsetY": 920
      },
      "combat": {
        "attack_range": 60,
        "contact_depth_threshold": 60
      },
      "descent": {
        "speed": 3,
        "start_y": -100,
        "threshold": 650
      },
      "phases": {
        "enrage_threshold": 0.5,
        "phase2_speed_mult": 2,
        "phase2_damage_mult": 2
      },
      "attacks": {
        "ground_pound": {
          "damage": 15,
          "radius": 120,
          "windup_ms": 800,
          "cooldown_ms": 5000
        },
        "charge": {
          "speed_mult": 4,
          "damage": 20,
          "duration_ms": 1000,
          "cooldown_ms": 7000
        },
        "summon": {
          "count": 3,
          "cooldown_ms": 10000
        }
      },
      "attack_cooldown_ms": 3000,
      "charge_range_mult": 2,
      "summon_pause_s": 0.5,
      "defeated_alpha": 0.5,
      "enrage_flash_ms": 200,
      "ground_pound_effects": {
        "shake_duration": 200,
        "shake_intensity": 0.01,
        "ring_initial_radius": 10,
        "ring_expand_duration": 400
      },
      "death_effects": {
        "shake_duration": 300,
        "shake_intensity": 0.025,
        "flash_duration": 200,
        "flash_r": 255,
        "flash_g": 200,
        "flash_b": 100
      },
      "animations": {
        "death_delay": 1000
      }
    },
    "key": {
      "speed": 50,
      "gravity": 0.3,
      "bounce_threshold": 2,
      "oscillation": {
        "frequency": 2,
        "amplitude": 30
      },
      "bounce_damping": 0.5,
      "offscreen_kill_distance": 200,
      "animations": {
        "fade_duration": 500,
        "fade_delay": 3000
      },
      "spawner": {
        "pool_size": 20,
        "delay_ms": 2000,
        "start_z": 500,
        "x_margin": 100,
        "y_margin_top": 600,
        "y_margin_bottom": 25
      }
    },
    "bomb": {
      "damage": 50,
      "explosion_radius": 250,
      "hitbox": {
        "width": 50,
        "height": 50
      },
      "effects": {
        "shake_duration": 150,
        "shake_intensity": 0.015
      },
      "spawner": {
        "pool_size": 10,
        "delay_ms": 5000,
        "start_z": 400,
        "x_margin": 100,
        "y_margin_top": 600,
        "y_margin_bottom": 25
      }
    },
    "chest": {
      "combat": {
        "interact_range": 100
      },
      "air_drop": {
        "delay_after_boss_ms": 1000,
        "landing_flash_color": 65416,
        "landing_flash_ms": 300,
        "landing_dust_color": 13412932,
        "landing_dust_radius": 80,
        "landing_dust_duration_ms": 400,
        "landing_shake_duration": 150,
        "landing_shake_intensity": 0.01
      }
    },
    "tresr_bot": {
      "health": 500,
      "damage": 50,
      "speed": 180,
      "air_drop": {
        "landing_flash_color": 65416,
        "landing_flash_ms": 500,
        "landing_dust_color": 8947848,
        "landing_dust_radius": 60,
        "landing_dust_duration_ms": 300,
        "landing_shake_duration": 100,
        "landing_shake_intensity": 0.005
      },
      "knockback": {
        "force": 120,
        "stun_ms": 200
      },
      "hitbox": {
        "radius": 25,
        "offsetX": 377,
        "offsetY": 705
      },
      "combat": {
        "attack_range": 80,
        "attack_cooldown_ms": 800,
        "target_switch_ms": 2000,
        "follow_distance": 80,
        "follow_speed_mult": 0.7
      },
      "lifetime": {
        "duration_ms": 30000,
        "fade_duration_ms": 1500,
        "spawn_flash_ms": 500
      },
      "special": {
        "cooldown_ms": 10000,
        "damage": 100,
        "radius": 120,
        "min_enemies": 3
      },
      "max_concurrent": 1,
      "max_drops_per_game": 5
    }
  },
  "scoring": {
    "key_collection": 100,
    "enemy_kill": 10,
    "boss_hit": 25,
    "super_hit": 25
  },
  "time_limit_seconds": 300,
  "max_keys": 150,
  "walkable_area": {
    "top_y": 600,
    "bottom_y": 700,
    "left_x": 0,
    "right_x": 1280
  },
  "physics": {
    "gravity": 0.8,
    "timestep": 0.01667
  },
  "combat": {
    "enemy_damage_cooldown_ms": 500,
    "enemy_spawn_offscreen_px": 80,
    "boss_melee_range_bonus": 20,
    "projectile_hit_radius": 40
  },
  "audio": {
    "default_music_volume": 0.75,
    "default_sfx_volume": 0.5,
    "crossfade_duration_ms": 2000,
    "crossfade_step_ms": 50,
    "preference_save_debounce_ms": 2000,
    "sfx_variants": {
      "bot_attack": 2,
      "bot_spawn": 10,
      "bot_special": 1,
      "countdown": 2,
      "death": 4,
      "explosion": 3,
      "game_over": 3,
      "hurt": 6,
      "key_collect": 3,
      "open_treasure_chest": 3,
      "powerup_collect": 1,
      "punch": 5,
      "victory": 3
    }
  },
  "vault": {
    "minimum_cap": 500,
    "tiers": {
      "easy": 5000,
      "normal": 25000,
      "hard": 100000
    },
    "difficulty_multipliers": {
      "easy": 0.6,
      "normal": 1,
      "hard": 1.5,
      "extreme": 2
    }
  }
} as const;
