// AUTO-GENERATED by bin/client-config.ts — DO NOT EDIT
import type { ConfigTypes } from "../../types/config.ts";

export function validateConfig(config: unknown): config is ConfigTypes {
  if (!config || typeof config !== "object") return false;
  const c = config as Record<string, unknown>;
  // Check configHash is 64-char hex
  if (typeof c.configHash !== "string" || !/^[a-f0-9]{64}$/.test(c.configHash))
    return false;
  // Check all required top-level keys
  if (!c.auth || typeof c.auth !== "object") return false;
  if (!c.app || typeof c.app !== "object") return false;
  if (!c.blockchain || typeof c.blockchain !== "object") return false;
  if (!c.wallet || typeof c.wallet !== "object") return false;
  if (!c.assets || typeof c.assets !== "object") return false;
  if (!c.display || typeof c.display !== "object") return false;
  if (!c.gameplay || typeof c.gameplay !== "object") return false;
  if (!c.sprites || typeof c.sprites !== "object") return false;
  if (!c.anti_cheat || typeof c.anti_cheat !== "object") return false;
  if (!c.credits || typeof c.credits !== "object") return false;
  if (!c.changelog || typeof c.changelog !== "object") return false;
  // Validate critical nested paths accessed before hash verification
  const gp = (c.gameplay as Record<string, unknown>);
  const ge = gp?.entities as Record<string, unknown> | undefined;
  const gep = ge?.player as Record<string, unknown> | undefined;
  const gfg = gp?.fee_gate as Record<string, unknown> | undefined;
  const au = (c.auth as Record<string, unknown>);
  const aa = au?.avalanche as Record<string, unknown> | undefined;
  if (!gp || !ge || !gep || !gfg || !au || !aa) return false;
  if (typeof gep.health !== "number" || gep.health <= 0) return false;
  if (typeof gep.speed !== "number" || gep.speed <= 0) return false;
  if (typeof gp.time_limit_seconds !== "number" || gp.time_limit_seconds <= 0) return false;
  if (typeof gfg.transaction_timeout_ms !== "number" || gfg.transaction_timeout_ms <= 0) return false;
  if (typeof aa.enabled !== "boolean") return false;
  return true;
}
