---
##################################################
# Name: cd-devenv-update.yaml
# Description: Workflow for Updating Developer Environment
##################################################

name: Devenv Update

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: read

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

  # SecretSpec
  SECRETSPEC_PROVIDER: env

defaults:
  run:
    shell: bash

jobs:
  update:
    name: Update

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ vars.CACHIX_CACHE_NAME }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: devenv_update
        name: Devenv update
        run: |
          devenv update

      - id: install_deps
        name: Install dependencies
        shell: devenv shell --quiet bash -- -e {0}
        run: |
          bun install

      - id: devenv_test
        name: Devenv test
        run: |
          devenv test

      - id: create_pull_request
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update devenv.lock"
          title: "chore: Update devenv.lock"
          body: "This PR updates the devenv input dependencies"
          branch: "update-devenv-lock"
          base: ${{ env.BRANCH_NAME_DEFAULT }}
          labels: "dependencies"
          assignees: "MAHDTech"
          reviewers: "MAHDTech"
          draft: false
          signoff: true
          delete-branch: true
          sign-commits: true
