---
##################################################
# Name: cd-foundry.yaml
# Description: Deploy Solidity contracts to testnet
##################################################

name: Foundry CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
      - trunk
    paths:
      - "contracts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  pull-requests: read
  statuses: write

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

  # SecretSpec
  SECRETSPEC_PROVIDER: env

  # Foundry
  FOUNDRY_PROFILE: ci

defaults:
  run:
    shell: bash

jobs:
  deploy-testnet:
    name: Deploy to Testnet (Fuji)

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    environment: Testnet

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ vars.CACHIX_CACHE_NAME }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: read_config
        name: Read config from tresr.yaml
        run: |
          {
            echo "RPC_URL=$(yq '.game.blockchain.avalanche.testnet.rpc_url' config/tresr.yaml)"
            echo "TOKEN_ADDRESS=$(yq '.game.blockchain.avalanche.testnet.tresr_token_contract' config/tresr.yaml)"
            echo "ORACLE_ADDRESS=$(yq '.game.blockchain.avalanche.testnet.oracle_address' config/tresr.yaml)"
            echo "ADMIN_ADDRESS=$(yq '.game.blockchain.avalanche.testnet.safe_address' config/tresr.yaml)"
          } >> "$GITHUB_OUTPUT"

      - id: deploy_fuji
        name: Deploy to Fuji
        shell: devenv shell --quiet bash -- -e {0}
        working-directory: contracts
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          TOKEN_ADDRESS: ${{ steps.read_config.outputs.TOKEN_ADDRESS }}
          ADMIN_ADDRESS: ${{ steps.read_config.outputs.ADMIN_ADDRESS }}
          ORACLE_ADDRESS: ${{ steps.read_config.outputs.ORACLE_ADDRESS }}
          SNOWTRACE_API_KEY: ${{ secrets.SNOWTRACE_API_KEY }}
        run: |
          forge script script/Vault.s.sol:DeployVault \
            --rpc-url ${{ steps.read_config.outputs.RPC_URL }} \
            --broadcast \
            --verify \
            --etherscan-api-key "$SNOWTRACE_API_KEY"
