---
##################################################
# Name: ci-devenv.yaml
# Description: Workflow for Developer Environment Testing
##################################################

name: Devenv CI

# prettier-ignore
on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - "main"
      - "master"
      - "trunk"
    paths:
      - .github/workflows/ci-devenv.yaml
      - devenv.nix
      - devenv.yaml
      - devenv.lock
      - src/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  pull-requests: write
  statuses: write

env:
  # GitHub
  PROJECT: ${{ github.repository }}
  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

  # Nix
  NIXPKGS_ALLOW_UNFREE: 1

  # SecretSpec
  SECRETSPEC_PROVIDER: env

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60
    continue-on-error: false

    environment: Testnet

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cachix-cache-name: ${{ vars.CACHIX_CACHE_NAME }}
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - id: install_deps
        name: Install dependencies
        shell: devenv shell --quiet bash -- -e {0}
        run: |
          bun install

      - id: devenv_test
        name: Devenv test
        run: |
          devenv test

      - if: always()
        uses: ./.github/actions/report-status
        with:
          result: ${{ steps.devenv_test.outcome }}
          success-description: "Devenv test passed!"
          failure-description: "Devenv test failed!"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          workflow-name: ${{ github.workflow }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          run-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
